### ISSUE TITLE
Chart.pluginService.register (undefined pluginService)

### ISSUE THREAD

**Issue by flieks** [reactchartjs/react-chartjs-2#671]
Hi, i have this after upgrading to 3.0.3.

![image](https://user-images.githubusercontent.com/5032389/117997078-f7b54e80-b342-11eb-98d2-afec40a715ce.png).

I added old code there. Not sure if i need to register stuff anymore but with the <Scatter>
I have this error:
This method is not implemented: either no adapter can be found or an incomplete integration was provided

What could this be ?

Greetings

**Comment by vaasu070** [comment]
try   `Chart.register(Zoom)`

**Comment by dikshantrajput** [comment]
> try `Chart.register()` instead of` Chart.pluginService.register()`

Getting this error:
Chart.register() is not a function

**Comment by vaasu070** [comment]
> > try `Chart.register()` instead of` Chart.pluginService.register()`
> 
> Getting this error:
> Chart.register() is not a function

which version of chartjs you are using?

**Comment by SliiCer** [comment]
Same for me! 
Can u please provide a sample code on how to use afterDraw/afterDatasetsDraw/afterLayout... plugins. With 3.x.x version.
I tried many differents way without result :s

**Comment by vaasu070** [comment]
> Same for me!
> Can u please provide a sample code on how to use afterDraw/afterDatasetsDraw/afterLayout... plugins. With 3.x.x version.
> I tried many differents way without result :s

Here is an [example](https://codesandbox.io/s/react-chartjs-histogram-chart-8y9e0?file=/src/App.js). This registers zoom plugin.

**Comment by SliiCer** [comment]
@vaasu070 Thanks a lot!!! You save my day ;)

**Comment by guimelao94** [comment]
@vaasu070  I'm getting this error when running your example 
![image](https://user-images.githubusercontent.com/26328677/132223194-ff726a69-1a6a-44a6-8697-d1233bfe0e20.png)

**Comment by vaasu070** [comment]
> @vaasu070 I'm getting this error when running your example
> ![image](https://user-images.githubusercontent.com/26328677/132223194-ff726a69-1a6a-44a6-8697-d1233bfe0e20.png)

Please check now, I just changed zoom pulugin to `1.0.0-beta.1`
